### ISSUE TITLE
탭바 무한스크롤 작업

### ISSUE THREAD

**Issue by tak8997** [boostcamp3-iOS/team-d2#18]
5개의 탭을 한쪽방향으로 계속 스크롤해도 연결된 탭 처럼 보이도록 무한정으로 스크롤 가능하게 하는 기능.

**Comment by gaonK** [comment]
탭바들이 원형(?)으로 도는 것 말하는 건가염

**Comment by tak8997** [comment]
넹.

**Comment by yoonhg84** [comment]
설명을 좀 더 자세히 써주세요~

**Comment by gaonK** [comment]
@yoonhg84 메인에 있는 탭바(캐시, 연재, 기다무, 완결, PICK) 부분을 계속 스크롤해도 연결되어 있는 것처럼 보이도록 하는 작업입니다. (ex. 마지막 탭인 PICK 탭에서 옆으로 넘기면 첫 번째 탭인 캐시 탭으로 넘어가는 기능)

**Comment by yoonhg84** [comment]
@gaonK 이슈 설명에 더 자세히 적어 달라는 의미였습니다.

**Comment by tak8997** [comment]
옙
